# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  serviceName: wazuh-cluster
  template:
    metadata:
      labels:
        app: wazuh-manager
      name: wazuh-manager
    spec:
      volumes:
        - name: config
          configMap:
            name: wazuh-manager-conf
      containers:
        - name: wazuh-manager
          image: 'wazuh/wazuh:3.13.0_7.7.1'
          resources:
            requests:
              cpu: 2
              memory: 1024Mi
            limits:
              cpu: 2
              memory: 2048Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager
              mountPath: /var/ossec/data
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1514
              name: logging
            - containerPort: 55000
              name: api
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
