apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds wazuh namespace to all resources.
namespace: wazuh

# resources to apply
resources:
- base.yaml
- elastic/elasticsearch-svc.yaml
- elastic/elasticsearch-sts.yaml
- kibana/kibana-svc.yaml
- kibana/kibana-deploy.yaml
- kibana/nginx-svc.yaml
- kibana/nginx-deploy.yaml
- wazuh/wazuh-svc.yaml
- wazuh/wazuh-conf.yaml
- wazuh/wazuh-sts.yaml
